// resources/js/contexts/admin/settings/gdpr/components/PrivacyFormComponent.vue
<template>
	<div class="card mb-3">
	  <div class="card-body">
      <h6 class="card-title mb-0">{{ $t('dashboard.settings.gdpr.gdpr_privacy_page') }}</h6>
      <form @submit.prevent="handleSubmit">
        <div id="privacy-editorjs" />
        
        <div class="d-flex align-items-center justify-content-start gap-2">
          <button type="submit" class="btn btn-primary me-2">{{ $t('dashboard.settings.update') }}</button>
          <a href="/privacy-policy" target="_blank">
            {{ $t('dashboard.settings.gdpr.gdpr_anchor') }} <i class="bi bi-arrow-right"></i>
          </a>
        </div>
      </form>
	  </div>
	</div>
</template>
  
<script setup>
  import { onMounted, ref } from "vue"
  import useSettingsStore from "@/js/contexts/admin/settings/general/stores/useSettingsStore"
  
  import EditorJS from '@editorjs/editorjs'
  import Header from '@editorjs/header'
  import Table from '@editorjs/table'
  import RawTool from '@editorjs/raw';
  
  const settingStore = useSettingsStore()
  const form = ref({})
  
  let editor
  
  onMounted( async() => {
    form.value = {
      gdpr_privacy_page: JSON.parse(settingStore.settings?.gdpr_privacy_page || '')
    }
    
    editor = new EditorJS({
      tools: {
      header: {
        class: Header,
        inlineToolbar: true,
        config: {
        levels: [2, 3, 4],
        defaultLevel: 3
        }
      },
      table: {
        class: Table,
        inlineToolbar: true,
        config: {
        rows: 2,
        cols: 3,
        },
      },
      raw: RawTool,
      },
      holder: 'privacy-editorjs',
      minHeight: 35,
      data: form.value.gdpr_privacy_page
    })
  })
  
  async function handleSubmit() {
    const data = await editor.save()
    
    settingStore.update({
      ...form.value,
      gdpr_privacy_page: JSON.stringify(data)
    })
  }
</script>

// resources/js/contexts/settings/components/PrivacyForm.tsx
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useOutletContext } from 'react-router-dom'
import { SettingsMap } from '@/contexts/settings/libs/types'
import { useSettings } from '@/contexts/settings/hooks/useSettings'
import { Editor } from '@/contexts/shared/components/ui/form/Editor'
import { OutputData } from '@editorjs/editorjs'
import { BaseButton } from '@/contexts/shared/components/Button'

export const PrivacyForm: React.FC = () => {
  const { t } = useTranslation()
  const { settings } = useOutletContext<{ settings: SettingsMap }>()
  const { update } = useSettings()

  const [initialData, setInitialData] = useState<OutputData | undefined>()

  useEffect(() => {
    try {
      if (settings?.gdpr_privacy_page) {
        setInitialData(JSON.parse(settings.gdpr_privacy_page))
      }
    } catch {
      setInitialData(undefined)
    }
  }, [settings])

  const handleChange = (newVal: OutputData) => {
    setInitialData(newVal)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    console.log('CMOOOON')
    update({
      gdpr_privacy_page: JSON.stringify(initialData),
    })
  }

  return (
    <div className="rounded bg-white p-4 shadow">
      <h6 className="mb-4 text-lg font-semibold">
        {t('dashboard.settings.gdpr.gdpr_privacy_page')}
      </h6>

      <form onSubmit={handleSubmit} className="space-y-4">
        {initialData && <Editor data={initialData} onChange={handleChange} />}

        <div className="flex items-center gap-4">
          <BaseButton
            title={t('dashboard.settings.update')}
            variant="primary"
            type="submit"
            className="rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
          />

          <a
            href="/privacy-policy"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1 text-sm text-blue-600 hover:underline"
          >
            {t('dashboard.settings.gdpr.gdpr_anchor')}
            <i className="bi bi-arrow-right" />
          </a>
        </div>
      </form>
    </div>
  )
}
