// resources/js/views/components/Settings/TranslateStrings.vue
<template>
    <div class="card">
        <div class="card-body">
            <h6 class="card-title">{{ $t('dashboard.settings.translations') }}</h6>

            <form @submit.prevent="handleUpdate">
                <div class="mb-5">
                    <label class="form-label">{{ $t('dashboard.settings.selected_locale') }}</label>
                    <div class="input-group">
                        <select class="form-select" v-model="selectedLocale" @change="changeLocale" required>
                            <option value="">{{ $t('dashboard.settings.select') }}</option>
                            <option v-for="lang in langStore.languages" :key="lang.code" :value="lang.code">{{lang.name}}</option>
                        </select>

                        <button class="btn btn-primary" type="button" @click="handleModal(true)">
                            {{ $t('dashboard.settings.new_localization') }}
                            <i class="bi bi-database-add"></i>
                        </button>
                    </div>
                    <small class="text-muted">{{ $t('dashboard.settings.locale_list_desc') }}</small>
                </div>

                <div class="table-container mb-3">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">{{ $t('dashboard.settings.source_text') }}</th>
                                <th scope="col">{{ $t('dashboard.settings.translation') }}</th>
                                <th class="text-end">
                                    <div class="input-group">
                                        <input type="text" class="form-control" :placeholder="$t('form.placeholder.search')" v-model="search">
                                        <button class="btn btn-outline-primary"><i class="m-0 bi bi-search"></i></button>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody v-if="getStrings.length > 0">
                            <tr v-for="(message, key) in getStrings" :key="message[0]">
                                <td class="text-muted">{{ message[0] }}</td>
                                <td colspan="2"><input type="text" :value="message[1]" @change="onWrite($event, key)" class="form-control border-0 bg-light"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <button type="submit" class="btn btn-primary me-2">{{ $t('dashboard.settings.update_translations') }}</button>
            </form>

            <modal-language v-if="showModal" @on-close="handleModal(false)" />
        </div>
    </div>
</template>

<script setup>
import { onBeforeMount, ref, computed } from "vue";
import { useLangStore } from "@/stores/lang";
import ModalLanguage from "./ModalLanguage.vue";

const app = window.AppConfig
const langStore = useLangStore()
const strings = ref([])
const selectedLocale = ref(null)
const showModal = ref(false)
const search = ref('')

const getStrings = computed(() =>
    strings.value.filter( el => el[1]
        .toLowerCase()
        .indexOf(search.value.toLowerCase()) >= 0))

onBeforeMount( async() => {
    selectedLocale.value = app.app_locale
    strings.value = Object.entries(app.locales[app.app_locale])
})

function handleUpdate() {
    langStore.update({strings: strings.value, code: selectedLocale.value})
}

function handleModal(value) {
    showModal.value = value
}

function changeLocale() {
    strings.value = Object.entries(app.locales[selectedLocale.value])
}

function onWrite($event, key) {
    strings.value[key][1] = $event.target.value
}
</script>

<style scoped>
.table tr {
    vertical-align: baseline;
}
.table td {
    padding: 5px;
}

.table th {
    padding: 15px 5px;
    font-weight: bold;
}

.table-container {
    height: 30rem;
}
table.table {
    display: flex;
    flex-flow: column;
    height: 100%;
    width: 100%;
}
table.table thead {
    flex: 0 0 auto;
    width: calc(100% - 0.9em);
}
table.table tbody {
    flex: 1 1 auto;
    display: block;
    overflow-y: scroll;
    font-size: 14px;
}
table.table tbody tr {
    width: 100%;
}
table.table thead, table tbody tr {
    display: table;
    table-layout: fixed;
}
.table td, .table th {
    white-space: normal;
}
</style>

// resources/js/contexts/settings/components/TranslateStrings.tsx
import React, { useEffect, useMemo, useState, ChangeEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { Card } from '@/contexts/shared/components/ui/Card'
import { Label } from '@/contexts/shared/components/ui/form/Label'
import { Select } from '@/contexts/shared/components/ui/form/Select'
import { BaseButton } from '@/contexts/shared/components/Button'
import { InputText } from '@/contexts/shared/components/ui/form/InputText'
import { CheckIcon } from '@/contexts/shared/components/Icons'
import { useLocalization } from '../hooks/useLocalization'
import { ModalLocalization } from './ModalLocalization'

export const TranslateStrings: React.FC = () => {
  const app = window.AppConfig
  const { t } = useTranslation()
  const { languages, updating, update, create } = useLocalization()

  const [strings, setStrings] = useState<[string, string][]>([])
  const [selectedLocale, setSelectedLocale] = useState<string>(app.app_locale)
  const [search, setSearch] = useState('')
  const [showModal, setShowModal] = useState(false)

  useEffect(() => {
    setStrings(Object.entries(app.locales[app.app_locale]))
  }, [app.app_locale])

  const getStrings = useMemo(() => {
    return strings.filter(el => el[1].toLowerCase().includes(search.toLowerCase()))
  }, [strings, search])

  const handleUpdate = () => {
    update({ strings, code: selectedLocale })
  }

  const handleCreate = (payload: { code: string; name: string }) => {
    create(payload)
  }

  const handleLocaleChange = (e: ChangeEvent<HTMLSelectElement>) => {
    const locale = e.target.value
    setSelectedLocale(locale)
    setStrings(Object.entries(app.locales[locale]))
  }

  const handleWrite = (e: ChangeEvent<HTMLInputElement>, key: number) => {
    const updated = [...strings]
    updated[key][1] = e.target.value
    setStrings(updated)
  }

  return (
    <Card>
      <h6 className="mb-3 text-lg font-semibold">{t('dashboard.settings.translations')}</h6>

      <form
        onSubmit={e => {
          e.preventDefault()
          handleUpdate()
        }}
      >
        <div className="mb-5">
          <Label>{t('dashboard.settings.selected_locale')}</Label>
          <div className="flex w-full justify-between gap-2">
            <Select name="locale" value={selectedLocale} required onChange={handleLocaleChange}>
              <option value="">{t('dashboard.settings.select')}</option>
              {languages?.map(lang => (
                <option key={lang.code} value={lang.code}>
                  {lang.name}
                </option>
              ))}
            </Select>

            <div className="text-end">
              <BaseButton
                title={t('dashboard.settings.new_localization')}
                variant="secondary"
                type="button"
                icon={<CheckIcon className="size-6" />}
                onClick={() => setShowModal(true)}
              />
            </div>
          </div>
          <small className="text-muted">{t('dashboard.settings.locale_list_desc')}</small>
        </div>

        {/* Tabla de traducciones */}
        <div className="mb-3 max-h-[30rem] overflow-y-scroll text-sm">
          <table className="w-full table-fixed border-collapse">
            <thead>
              <tr>
                <th className="p-2 text-left font-semibold">
                  {t('dashboard.settings.source_text')}
                </th>
                <th className="p-2 text-left font-semibold">
                  {t('dashboard.settings.translation')}
                </th>
                <th className="p-2 text-right">
                  <InputText
                    type="text"
                    className="font-medium"
                    placeholder={t('form.placeholder.search')}
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              {getStrings.length > 0 &&
                getStrings.map((message, key) => (
                  <tr key={message[0]}>
                    <td className="p-2 text-gray-500">{message[0]}</td>
                    <td colSpan={2} className="p-2">
                      <InputText
                        type="text"
                        value={message[1]}
                        onChange={e => handleWrite(e, key)}
                        className="border-0 bg-gray-100"
                      />
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>

        <BaseButton
          title={t('dashboard.settings.update_translations')}
          variant="primary"
          type="submit"
          loading={updating}
          className="me-2"
        />
      </form>

      {showModal && (
        <ModalLocalization onCreate={handleCreate} onClose={() => setShowModal(false)} />
      )}
    </Card>
  )
}
